# Generated by Django 3.1.7 on 2021-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
